apiVersion: v1
kind: ReplicationController
metadata:
  name: carshare-api
  labels:
    app: carshare-api
spec:
  replicas: 1
  selector:
    app: carshare-api
  template:
    metadata:
      labels:
        app: carshare-api
    spec:
      containers:
      - image: lewiswatson/carshare-back:0.4.1
        imagePullPolicy: Always
        name: carshare-api
        ports:
        - containerPort: 31415
          hostPort: 31415
        args:
        - --mgoURL=mongo
        env:
        - name: GIN_MODE
          value: release